# Generated by Django 5.2.10 on 2026-01-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
